### ISSUE TITLE
Englischer Claim

### ISSUE THREAD

**Issue by Antujin** [fsphys-muenster/presentation-template#3]
Der englische Claim funktioniert nicht weil in der wwustyle.sty anstelle des nötigen \renewcommand{...} nur ein \newcommand{} verwendet wird. Die Änderung erlaubt auch die Verwendung des englischen Claims. Das könnte u.a. für Erasmus Begrüßungen u.ä. interessant sein.

**Comment by Socob** [comment]
Guter Hinweis!

Behoben in 19b8449.
